---
- name: Generate OpenSSL CA private key
  community.crypto.openssl_privatekey:
    path: ssl/ca.key
    size: 2048

- name: Generate OpenSSL CSR for CA
  community.crypto.openssl_csr:
    path: ssl/ca.csr
    privatekey_path: ssl/ca.key
    common_name: "{{ mongodb_ca_common_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
    country_name: IN
    organization_name: "MongoDB"

- name: Generate OpenSSL CA certificate
  community.crypto.x509_certificate:
    path: ssl/ca.crt
    csr_path: ssl/ca.csr
    privatekey_path: ssl/ca.key
    provider: selfsigned

- name: generate pem file from key and certificate
  copy:
    content: |
      {{ lookup('file', 'ssl/ca.key') }}
      {{ lookup('file', 'ssl/ca.crt') }}
    dest: "ssl/ca.pem"